/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/


-- Total customers by countries
SELECT country,
COUNT(DISTINCT customer_key) total_customers
from DataWarehouseAnalytics..[gold.dim_customers] 
Group by country
Order by total_customers DESC

--Total customers by gender
SELECT gender,
COUNT(DISTINCT customer_key) total_customers_by_gender
from DataWarehouseAnalytics..[gold.dim_customers] 
Group by gender
Order by total_customers_by_gender DESC

--Total product by category
SELECT category,
COUNT(DISTINCT product_id) total_product
from DataWarehouseAnalytics..[gold.dim_products] 
Group by category
Order by total_product DESC

--average cost in each category
SELECT category,
AVG(convert(int, cost)) avg_cost
from DataWarehouseAnalytics..[gold.dim_products] 
Group by category
Order by avg_cost DESC

--Total revenue generated by each category
Select 
category,
SUM(convert(int, s.sales_amount)) revenue
from DataWarehouseAnalytics..[gold.fact_sales] s left join 
 DataWarehouseAnalytics..[gold.dim_products] p on s.product_key = p.product_key
 Group by category
 Order by revenue DESC

 --- TOTAL REVENUE GENERATED BY EACH CUSTOMER

 SELECT c.customer_key, c.first_name, c.last_name,
 SUM(convert(int, s.sales_amount)) total_revenue
 from DataWarehouseAnalytics..[gold.fact_sales] s LEFT JOIN
DataWarehouseAnalytics..[gold.dim_customers] c on s.customer_key = c.customer_key
Group by c.customer_key, c.first_name, c.last_name
Order by total_revenue DESC

--- DISTRIBUTION OF SOLD ITEMS ACROSS COUNTRIES
 SELECT c.country,
 SUM(convert(int, s.quantity)) total_sold_items
 from DataWarehouseAnalytics..[gold.fact_sales] s LEFT JOIN
DataWarehouseAnalytics..[gold.dim_customers] c on s.customer_key = c.customer_key
Group by c.country
Order by total_sold_items DESC





